remote_theme: "mmistakes/so-simple-theme@3.2.0"

locale: tr-TR
title: "Mehmet Aykurt Kişisel Web Sitesi"
description: "Mehmet Aykurt’un şiir, yazı, müzik ve NVDA eklenti projelerini içeren kişisel web sitesi."
url: "https://mehmetaykurt.com.tr"
baseurl: ""
repository: "MehmetAykurt/mehmetaykurt.github.io"

author:
  name: "Mehmet Aykurt"
  email: "m.aykurt38@gmail.com"

timezone: Europe/Istanbul
date_format: "%d.%m.%Y"

read_time: false
words_per_minute: 200

search_full_content: true

copyright: "© Mehmet Aykurt 2026 — Tüm hakları saklıdır."

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
