title: "Mehmet Aykurt - Kişisel Web Sitesi"
description: "Şiirler ve Çalışmalar"
url: "https://mehmetaykurt.com.tr"
baseurl: ""

remote_theme: "mmistakes/so-simple-theme"

plugins:
  - jekyll-remote-theme

search: true

footer:
  copyright: "Mehmet Aykurt - 2026"